language: node_js

os:
  - osx
  - linux

node_js:
  - 6
  - 8
  - 10
  - node

before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew install redis; fi
  - redis-server --version
