language: node_js

os:
  # Disabled for now, too slow
  # - osx
  - linux

node_js:
  - 6
  - 8
  - 10
  - node

before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then HOMEBREW_NO_INSTALL_CLEANUP=1 brew install redis; fi
  - redis-server --version
